name: build_and_deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout branch
      uses: actions/checkout@v1

    - name: Set enviroment variable
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:11})

    - name: Build the Docker image
      run: docker build -t docker.pkg.github.com/penuts7644/immuno-probs-docker/immuno-probs:${{ env.RELEASE_VERSION }} .

    - name: Deploy the Docker image
      if: success()
      run: |
        docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
        docker push docker.pkg.github.com/penuts7644/immuno-probs-docker/immuno-probs:${{ env.RELEASE_VERSION }}
